# Generated by Django 4.2.3 on 2023-09-25 15:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BrandLogo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brandname", models.CharField(default="", max_length=50)),
                ("brandimage", models.ImageField(default="", upload_to="images")),
            ],
        ),
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("isshared", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Homeslider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sliderimg", models.ImageField(default="", upload_to="images")),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("email", models.CharField(max_length=40)),
                ("phone", models.CharField(max_length=15)),
                ("password", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Trip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cname", models.CharField(max_length=50)),
                ("sdate", models.CharField(max_length=50)),
                ("edate", models.CharField(max_length=50)),
                (
                    "car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trip",
                        to="app.car",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="app.car",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_reviews",
                        to="app.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Rating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rating", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratings",
                        to="app.car",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_ratings",
                        to="app.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Price",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.IntegerField()),
                ("isFilled", models.BooleanField(default=False)),
                (
                    "car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="car_price",
                        to="app.car",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("N1", models.CharField(max_length=100)),
                ("N2", models.CharField(max_length=100)),
                ("N3", models.CharField(max_length=100)),
                ("N4", models.CharField(max_length=100)),
                ("N5", models.CharField(max_length=100)),
                (
                    "car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="host_notification",
                        to="app.car",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Income",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cname", models.CharField(max_length=50)),
                ("cinc", models.CharField(max_length=50)),
                ("sidate", models.CharField(max_length=50)),
                ("eidate", models.CharField(max_length=50)),
                (
                    "car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="income",
                        to="app.car",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HostBio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Gphone", models.CharField(max_length=15)),
                ("Himage", models.ImageField(default="", upload_to="images")),
                ("Hbio", models.CharField(max_length=100)),
                ("isFilled", models.BooleanField(default=False)),
                (
                    "car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="host_bio",
                        to="app.car",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CarImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Image1", models.ImageField(default="", upload_to="images")),
                ("Image2", models.ImageField(default="", upload_to="images")),
                ("Image3", models.ImageField(default="", upload_to="images")),
                ("Image4", models.ImageField(default="", upload_to="images")),
                ("Image5", models.ImageField(default="", upload_to="images")),
                ("Image6", models.ImageField(default="", upload_to="images")),
                ("Image7", models.ImageField(default="", upload_to="images")),
                ("isFilled", models.BooleanField(default=False)),
                (
                    "car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="car_image",
                        to="app.car",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CarDate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sharesdate", models.DateField(default="", max_length=50)),
                ("shareedate", models.DateField(default="", max_length=50)),
                (
                    "car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="car_date",
                        to="app.car",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="car",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app.user"
            ),
        ),
        migrations.CreateModel(
            name="Bank",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("acc_no", models.CharField(default="1234567891234560", max_length=20)),
                ("ifsc", models.CharField(default="12334", max_length=20)),
                ("pan", models.CharField(default="1234", max_length=20)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bank",
                        to="app.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AddCar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("License", models.CharField(max_length=15)),
                ("CarBrand", models.CharField(max_length=20)),
                ("CarModel", models.CharField(max_length=50)),
                ("CarVariant", models.CharField(max_length=50)),
                ("CarCity", models.CharField(max_length=20)),
                ("CarYear", models.CharField(max_length=4)),
                ("CarFuel", models.CharField(max_length=12)),
                ("CarTrans", models.CharField(max_length=12)),
                ("CarSeat", models.CharField(default="5 Seats", max_length=12)),
                ("CarKm", models.CharField(max_length=25)),
                ("CarChassisNo", models.CharField(max_length=17)),
                ("isFilled", models.BooleanField(default=False)),
                (
                    "car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="added_cars",
                        to="app.car",
                    ),
                ),
            ],
        ),
    ]
