# Generated by Django 4.2.3 on 2023-08-22 03:21

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("N1", models.CharField(max_length=100)),
                ("N2", models.CharField(max_length=100)),
                ("N3", models.CharField(max_length=100)),
                ("N4", models.CharField(max_length=100)),
                ("N5", models.CharField(max_length=100)),
                (
                    "car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="host_notification",
                        to="app.car",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HostBio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Hname", models.CharField(max_length=40)),
                ("Hemail", models.CharField(max_length=30)),
                ("Hphone", models.CharField(max_length=15)),
                ("Gphone", models.CharField(max_length=15)),
                ("Himage", models.ImageField(default="", upload_to="images")),
                ("Hbio", models.CharField(max_length=100)),
                (
                    "car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="host_bio",
                        to="app.car",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CarImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Image1", models.ImageField(default="", upload_to="images")),
                ("Image2", models.ImageField(default="", upload_to="images")),
                ("Image3", models.ImageField(default="", upload_to="images")),
                ("Image4", models.ImageField(default="", upload_to="images")),
                ("Image5", models.ImageField(default="", upload_to="images")),
                ("Image6", models.ImageField(default="", upload_to="images")),
                ("Image7", models.ImageField(default="", upload_to="images")),
                (
                    "car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="car_image",
                        to="app.car",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AddCar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("License", models.CharField(max_length=15)),
                ("CarBrand", models.CharField(max_length=20)),
                ("CarModel", models.CharField(max_length=50)),
                ("CarVariant", models.CharField(max_length=50)),
                ("CarCity", models.CharField(max_length=20)),
                ("CarYear", models.CharField(max_length=4)),
                ("CarFuel", models.CharField(max_length=12)),
                ("CarTrans", models.CharField(max_length=12)),
                ("CarKm", models.CharField(max_length=25)),
                ("CarChassisNo", models.CharField(max_length=17)),
                (
                    "car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="added_cars",
                        to="app.car",
                    ),
                ),
            ],
        ),
    ]
