# Generated by Django 4.2.3 on 2023-09-25 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_user_password"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="addcar",
            name="CarVariant",
        ),
        migrations.AddField(
            model_name="hostbio",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="host_user",
                to="app.user",
            ),
            preserve_default=False,
        ),
    ]
